### ISSUE TITLE
itemName not functional.

### ISSUE THREAD

**Issue by mibby** [JamieSinn/TrailGUI#21]
TrailGUI dev 34

The itemName config option is not functional. Instead of the trail names in the GUI being (default) orange colored, they are italicized and ignoring the config setting.

```
  MagicCrit:
    type: CRIT_MAGIC
    #The location the particle effect is displayed.
    displayLocation: 0.2
    #The amount of particles displayed.
    amount: 2
    #The speed the particles are displayed.
    speed: 1
    #The distance before unrendering the particle effect.
    range: 20
    #The inventory slot the item is put in.
    order: 12
    #The items type.
    itemType: POTION
    #The items name.
    itemName: "&6MagicCrit"
    #Whether or not the lore is enabled.
    loreEnabled: false
    #The text written on lore line one.
    loreLineOne: "Example"
    #The text written on lore line two.
    loreLineTwo: "Example"
    #The text written on lore line three.
    loreLineThree: "Example"
```

![link](http://i.imgur.com/MDDmkTa.png)
